import os
import re
import sys
import time
import socket
import subprocess
import threading
import psutil
import requests
from services.repo_analyzer import load_store, call_groq_llm
from services.ml_engine import detect_log_anomalies

ACTIVE_DEPLOYMENTS = {}
LOGS_DIR = "./deploy_logs"
os.makedirs(LOGS_DIR, exist_ok=True)

def find_free_port(start_port=8010, max_port=8999):
    for port in range(start_port, max_port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(('127.0.0.1', port))
                return port
            except OSError:
                continue
    return 8080

def inspect_env_vars(repo_path: str, file_list: list):
    env_keys = {}

    # Check .env.example / .env.sample / .env
    for fname in ['.env.example', '.env.sample', '.env.local.example', '.env']:
        for rel in file_list:
            if os.path.basename(rel).lower() == fname:
                full_path = os.path.join(repo_path, rel)
                try:
                    with open(full_path, 'r', encoding='utf-8', errors='ignore') as f:
                        for line in f:
                            line = line.strip()
                            if line and not line.startswith('#') and '=' in line:
                                k, v = line.split('=', 1)
                                env_keys[k.strip()] = v.strip().strip("'\"")
                except Exception:
                    pass

    py_env_regex = re.compile(r"""(?:os\.environ\.get|os\.getenv)\s*\(\s*['"]([A-Za-z0-9_]+)['"](?:\s*,\s*['"](.*?)['"])?\s*\)""")
    js_env_regex = re.compile(r"""(?:process\.env\.([A-Za-z0-9_]+)|process\.env\[['"]([A-Za-z0-9_]+)['"]\])""")

    for rel in file_list[:80]:
        ext = os.path.splitext(rel)[1].lower()
        if ext in ['.py', '.js', '.ts', '.jsx', '.tsx']:
            full_path = os.path.join(repo_path, rel)
            try:
                content = open(full_path, 'r', encoding='utf-8', errors='ignore').read(30000)
                if ext == '.py':
                    for match in py_env_regex.finditer(content):
                        k = match.group(1)
                        default_val = match.group(2) or ""
                        if k not in env_keys and not k.startswith(('PATH', 'PYTHON', 'TERM')):
                            env_keys[k] = default_val
                else:
                    for match in js_env_regex.finditer(content):
                        k = match.group(1) or match.group(2)
                        if k and k not in env_keys and not k.startswith(('NODE_ENV', 'PATH')):
                            env_keys[k] = ""
            except Exception:
                pass

    return [
        {"key": k, "default_value": v, "required": not bool(v)}
        for k, v in env_keys.items()
    ]

def generate_dockerfile(repo_path: str, tech_stack: list, file_list: list):
    stack_names = [t['name'].lower() if isinstance(t, dict) else str(t).lower() for t in tech_stack]
    filenames = [os.path.basename(f).lower() for f in file_list]

    if 'fastapi' in stack_names or 'django' in stack_names or 'flask' in stack_names or 'python' in stack_names:
        entry_cmd = '["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]' if 'fastapi' in stack_names else '["python", "main.py"]'
        dockerfile = f"""# Multi-Stage Python Dockerfile generated by NeuroDeploy
FROM python:3.11-slim as builder

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential && rm -rf /var/lib/apt/lists/*

COPY requirements*.txt .
RUN pip install --no-cache-dir --user -r requirements.txt || true

FROM python:3.11-slim
WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY . .

ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1
ENV PORT=8000
EXPOSE 8000

CMD {entry_cmd}
"""
    elif 'next.js' in stack_names or 'react' in stack_names or 'node.js' in stack_names:
        dockerfile = """# Multi-Stage Node.js Dockerfile generated by NeuroDeploy
FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps || npm install

COPY . .
RUN npm run build --if-present

FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000

COPY --from=builder /app ./
CMD ["npm", "start"]
"""
    elif 'go' in stack_names:
        dockerfile = """# Multi-Stage Go Dockerfile generated by NeuroDeploy
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 8080
CMD ["./server"]
"""
    else:
        dockerfile = """# Static / Web Dockerfile generated by NeuroDeploy
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"""

    compose = f"""# docker-compose.yml generated by NeuroDeploy
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped
"""

    dockerignore = """.git
node_modules
__pycache__
.venv
venv
.next
dist
build
*.log
.env
"""

    return {
        "dockerfile": dockerfile.strip(),
        "compose": compose.strip(),
        "dockerignore": dockerignore.strip()
    }


def launch_app(repo_id: str, env_vars: dict = None, custom_command: str = None):
    store = load_store(repo_id)
    if not store:
        raise ValueError("Repository metadata not found. Please index the repository first.")

    repo_path = os.path.abspath(store["repo_path"])
    file_list = store.get("file_list", [])
    tech_stack = store.get("tech_stack", [])
    stack_names = [t['name'].lower() if isinstance(t, dict) else str(t).lower() for t in tech_stack]

    port = find_free_port()
    deploy_id = f"deploy_{repo_id}_{int(time.time())}"
    log_file_path = os.path.abspath(os.path.join(LOGS_DIR, f"{deploy_id}.log"))

    if custom_command and custom_command.strip():
        cmd = custom_command.strip()
    else:
        py_files = [f for f in file_list if f.endswith('.py')]
        if 'fastapi' in stack_names or any('main.py' in f for f in py_files):
            # Check if backend directory exists
            if os.path.exists(os.path.join(repo_path, 'backend', 'main.py')):
                cmd = f'"{sys.executable}" -m uvicorn backend.main:app --host 0.0.0.0 --port {port}'
            elif os.path.exists(os.path.join(repo_path, 'main.py')):
                cmd = f'"{sys.executable}" -m uvicorn main:app --host 0.0.0.0 --port {port}'
            elif os.path.exists(os.path.join(repo_path, 'app.py')):
                cmd = f'"{sys.executable}" app.py'
            else:
                cmd = f'"{sys.executable}" {py_files[0]}'
        elif 'node.js' in stack_names or any(f == 'package.json' for f in file_list):
            cmd = f'npm start -- --port {port}'
        else:
            cmd = f'"{sys.executable}" -m http.server {port}'

    run_env = os.environ.copy()
    run_env["PORT"] = str(port)
    run_env["HOST"] = "0.0.0.0"
    if env_vars:
        for k, v in env_vars.items():
            run_env[str(k)] = str(v)

    log_file = open(log_file_path, "w", encoding="utf-8")
    log_file.write(f"=== NeuroDeploy Sandbox Launched at {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n")
    log_file.write(f"Command: {cmd}\n")
    log_file.write(f"Port: {port}\n")
    log_file.write(f"===========================================================\n\n")
    log_file.flush()

    try:
        proc = subprocess.Popen(
            cmd,
            cwd=repo_path,
            env=run_env,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            shell=True,
            text=True
        )
    except Exception as e:
        log_file.write(f"Launch failed: {str(e)}\n")
        log_file.close()
        raise RuntimeError(f"Failed to start process: {str(e)}")

    deployment_data = {
        "deploy_id": deploy_id,
        "repo_id": repo_id,
        "pid": proc.pid,
        "port": port,
        "url": f"http://localhost:{port}",
        "cmd": cmd,
        "log_file": log_file_path,
        "start_time": time.time(),
        "status": "starting",
        "proc": proc
    }
    ACTIVE_DEPLOYMENTS[deploy_id] = deployment_data

    def probe_health():
        time.sleep(2)
        if proc.poll() is not None:
            deployment_data["status"] = "failed"
            return

        for _ in range(5):
            try:
                res = requests.get(f"http://127.0.0.1:{port}", timeout=1)
                if res.status_code < 500:
                    deployment_data["status"] = "running"
                    return
            except Exception:
                time.sleep(1)

        deployment_data["status"] = "running" if proc.poll() is None else "failed"

    threading.Thread(target=probe_health, daemon=True).start()

    return {
        "deploy_id": deploy_id,
        "status": "running",
        "port": port,
        "url": f"http://localhost:{port}",
        "pid": proc.pid,
        "command": cmd
    }

def stop_app(deploy_id: str):
    if deploy_id not in ACTIVE_DEPLOYMENTS:
        return {"status": "not_found", "message": "Deployment ID not active."}

    data = ACTIVE_DEPLOYMENTS[deploy_id]
    proc = data.get("proc")
    pid = data.get("pid")

    try:
        if pid:
            parent = psutil.Process(pid)
            for child in parent.children(recursive=True):
                child.terminate()
            parent.terminate()
    except Exception:
        pass

    data["status"] = "stopped"
    return {"status": "stopped", "deploy_id": deploy_id}

def get_app_status(deploy_id: str):
    if deploy_id not in ACTIVE_DEPLOYMENTS:
        return {"status": "stopped", "is_running": False}

    data = ACTIVE_DEPLOYMENTS[deploy_id]
    pid = data.get("pid")
    port = data.get("port")
    proc = data.get("proc")

    is_running = False
    cpu_percent = 0.0
    memory_mb = 0.0

    if pid:
        try:
            p = psutil.Process(pid)
            if p.is_running() and p.status() != psutil.STATUS_ZOMBIE:
                is_running = True
                cpu_percent = p.cpu_percent(interval=0.1)
                memory_mb = round(p.memory_info().rss / (1024 * 1024), 2)
        except Exception:
            is_running = False

    uptime_sec = int(time.time() - data.get("start_time", time.time())) if is_running else 0

    return {
        "deploy_id": deploy_id,
        "is_running": is_running,
        "status": "running" if is_running else ("failed" if data.get("status") == "failed" else "stopped"),
        "port": port,
        "url": data.get("url"),
        "pid": pid,
        "uptime_seconds": uptime_sec,
        "cpu_percent": cpu_percent,
        "memory_mb": memory_mb
    }


def get_app_logs(deploy_id: str, tail_lines=100):
    if deploy_id not in ACTIVE_DEPLOYMENTS:
        # Check if log file exists on disk
        log_file_path = os.path.join(LOGS_DIR, f"{deploy_id}.log")
    else:
        log_file_path = ACTIVE_DEPLOYMENTS[deploy_id].get("log_file")

    if not log_file_path or not os.path.exists(log_file_path):
        return {"logs": [], "anomalies_detected": 0}

    try:
        with open(log_file_path, "r", encoding="utf-8", errors="ignore") as f:
            lines = [line.rstrip() for line in f.readlines()][-tail_lines:]

        analyzed = detect_log_anomalies(lines)
        anomaly_count = sum(1 for a in analyzed if a["is_anomaly"])

        return {
            "logs": analyzed,
            "raw_text": "\n".join(lines),
            "anomalies_detected": anomaly_count
        }
    except Exception as e:
        return {"logs": [{"line": f"Error reading logs: {str(e)}", "is_anomaly": True}], "anomalies_detected": 1}


def diagnose_failure_with_ai(repo_id: str, error_logs: str, custom_context: str = ""):
    store = load_store(repo_id) or {}
    tech_stack = store.get("tech_stack", [])
    stack_str = ', '.join([t['name'] if isinstance(t, dict) else str(t) for t in tech_stack])

    messages = [
        {
            "role": "system",
            "content": "You are an expert DevOps engineer and AI Build Doctor. Analyze errors concisely and provide the exact fix."
        },
        {
            "role": "user",
            "content": f"""A deployment failed for a {stack_str} application.

Error Output:
{error_logs[:2000]}

{f"Context: {custom_context}" if custom_context else ""}

Provide:
1. Root cause summary (1-2 sentences)
2. Exact step or command to resolve it
3. Fixed configuration or code snippet if relevant."""
        }
    ]

    diagnosis = call_groq_llm(messages, max_tokens=600)
    return diagnosis
